### ISSUE TITLE
1.x: REST request not reaching the couchbase lite java listener.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-listener#83] opened 2017-08-28 14:36 UTC
Hi Folks,

1)App design similar to Couchbase-Lite-PhoneGap-Plugin
https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin

2) **App HTML/JS code does REST using -->>> modules.js(https request formation and timeouts) ---> Android Webview --->> couchbase lite java listener**

https://github.com/couchbaselabs/TodoLite-PhoneGap/blob/f1a810f9408a9807f3bf25ae69ba1d6a6aaee71c/js/modules.js

3)Heartbeat for DB changes(_changes) is 5 mins.

4) After idle the REST request from HTML/JS fails to get response from server.

**Logs Analysis:**

**Success case:**

**App JS:**

```
[08/28 17:40:08:006] [HTML5LOG] cblPtxInterface.syncManager()-> doCancelPost()-> Stop Sync = {"target":"ptxdata","source":{"url":"https://AAAAAAAAAAAA:XXXXXXXXXXXXXXXXX@mydomain/data"},"continuous":true,"filter":"sync_gateway/bychannel","query_params":{"channels":"PTX-919480109390-meta-CH,919480109390-CH"}}
[08/28 17:40:08:013] [HTML5LOG] ReSTCBL ::: Request started::{"id":"139: POST https://:@localdomain:14480/_replicate"}
[08/28 17:40:08:083] [HTML5LOG] ReSTCBL ::: Got response::{"id":"139: POST https://:@localdomain:14480/_replicate","status":200}
```

**App Webview:**
```
[08/28 17:40:08:019] WhitelistPlugin ---------- cblURL: https://:@localdomain:14480/
[08/28 17:40:08:020] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
```
**Couchbase Logs:**

```
 [08/28 05:40:08.061] [4] Listener: [REQUEST] (Acme.Utils.ThreadPool(1)-PooledThread: Acme.Serve.Serve$ServeConnection@2116a1d0) POST: https://localdomain:14480/_replicate
[08/28 05:40:08.061] [4] Listener: authHeader is null
[08/28 05:40:08.062] [4] Listener: Not enforcing basic auth -- allowedCredentials null or empty
[08/28 05:40:08.062] [4] Listener: remoteURL() addr=localdomain
[08/28 05:40:08.064] [4] Database: getDatabase() com.couchbase.lite.Manager@1da33ad9 com.couchbase.lite.Database@37445c9e[/data/data/com.xxx.app/files/data.cblite2]
[08/28 05:40:08.068] [4] Sync: PullerInternal{https://---:---@mydomain/data, pull, 1856e} [fireTrigger()] => STOP_GRACEFUL
[08/28 05:40:08.069] [4] Listener: RouterCallbackBlock.onResponseReady() START
[08/28 05:40:08.069] [16] Sync: firing trigger: STOP_GRACEFUL
[08/28 05:40:08.070] [4] Listener: RouterCallbackBlock.onResponseReady() END
[08/28 05:40:08.072] [4] Listener: CountDownLatch.await() START
[08/28 05:40:08.072] [4] Listener: CountDownLatch.await() END
```

**Failure case:**

**App JS:**

```
Line 2050: [08/28 17:54:22:685] [HTML5LOG] ReSTCBL ::: Request started::{"id":"142: GET https://:@localdomain:14480/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}
Line 2052: [08/28 17:59:22:697] [HTML5LOG] ReSTCBL ::: Request started::{"id":"143: GET https://:@localdomain:14480/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}
Line 2054: [08/28 18:04:22:720] [HTML5LOG] ReSTCBL ::: Request started::{"id":"144: GET https://:@localdomain:14480/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}
Line 2075: [08/28 18:08:24:393] [HTML5LOG] ReSTCBL ::: Request started::{"id":"145: POST https://:@localdomain:14480/_replicate"}
Line 2084:  History url = https://:@localdomain:14480/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false
Line 2097:  History url = https://:@localdomain:14480/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false
Line 2105:  History url = https://:@localdomain:14480/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false
Line 2113:  History url = https://:@localdomain:14480/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false
Line 2121:  History url = https://:@localdomain:14480/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false
Line 2375: [08/28 18:09:22:718] [HTML5LOG] ReSTCBL ::: Request started::{"id":"146: GET https://:@localdomain:14480/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}
Line 2423: [08/28 18:13:25:463] [HTML5LOG] ReSTCBL ::: Request started::{"id":"147: POST https://:@localdomain:14480/_replicate"}
Line 2425: [08/28 18:14:22:733] [HTML5LOG] ReSTCBL ::: Request started::{"id":"148: GET https://:@localdomain:14480/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}
Line 2429:  History url = https://:@localdomain:14480/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false
Line 2464: [08/28 18:18:26:561] [HTML5LOG] ReSTCBL ::: Request started::{"id":"149: POST https://:@localdomain:14480/_replicate"}
Line 2466: [08/28 18:19:22:744] [HTML5LOG] ReSTCBL ::: Request started::{"id":"150: GET https://:@localdomain:14480/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}
Line 2469: [08/28 18:20:04:296] [HTML5LOG] ReSTCBL ::: Request started::{"id":"151: POST https://:@localdomain:14480/data/_compact"}
Line 2502: [08/28 18:23:27:621] [HTML5LOG] ReSTCBL ::: Request started::{"id":"152: POST https://:@localdomain:14480/_replicate"}
Line 2504: [08/28 18:24:22:756] [HTML5LOG] ReSTCBL ::: Request started::{"id":"153: GET https://:@localdomain:14480/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}
Line 2516: [08/28 18:29:22:768] [HTML5LOG] ReSTCBL ::: Request started::{"id":"154: GET https://:@localdomain:14480/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}
Line 2526: [08/28 18:33:06:878] [HTML5LOG] ReSTCBL ::: Request started::{"id":"155: GET https://:@localdomain:14480/_active_tasks"}
Line 2528: [08/28 18:34:22:768] [HTML5LOG] ReSTCBL ::: Request started::{"id":"156: GET https://:@localdomain:14480/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}
Line 2549: [08/28 18:37:02:654] [HTML5LOG] ReSTCBL ::: Request started::{"id":"157: POST https://:@localdomain:14480/_replicate"}
Line 2553:  History url = https://:@localdomain:14480/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false
Line 2566:  History url = https://:@localdomain:14480/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false
Line 2843: [08/28 18:37:28:147] [HTML5LOG] ReSTCBL ::: Request started::{"id":"158: GET https://:@localdomain:14480/data/s919480109390_ptx1503925648131_meta.doc"}
Line 2901:  History url = https://:@localdomain:14480/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false
```

**App Webview**
```
Line 42946: [08/28 17:54:22:697] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43015: [08/28 17:59:22:710] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43090: [08/28 18:04:22:736] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43145: [08/28 18:08:24:400] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43158: [08/28 18:08:25:491] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43161: [08/28 18:08:27:061] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43164: [08/28 18:08:28:078] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43167: [08/28 18:08:29:073] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43170: [08/28 18:08:32:186] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43343: [08/28 18:09:22:721] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43427: [08/28 18:13:25:467] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43429: [08/28 18:14:22:744] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43432: [08/28 18:14:31:067] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43462: [08/28 18:18:26:572] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43464: [08/28 18:19:22:755] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43478: [08/28 18:20:04:301] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43552: [08/28 18:23:27:633] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43554: [08/28 18:24:22:763] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43585: [08/28 18:29:22:777] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43647: [08/28 18:33:06:890] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43676: [08/28 18:34:22:771] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43735: [08/28 18:37:02:657] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43738: [08/28 18:37:03:966] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43741: [08/28 18:37:05:674] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43830: [08/28 18:37:28:150] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
Line 43856: [08/28 18:37:36:267] WhitelistPlugin ---------- CBL URL allowed to Navigate -----
```
3

**Couchbase Logs:**

**Do not see any request hitting the server.**

**Detail Logs:**

**App JS:**
https://gist.github.com/NitzDKoder/a4562f511329919caa44acbe5bee7d47

**App Webview**
https://gist.github.com/NitzDKoder/f2ceed30c41f6bfa8a2127bbbde06195

**Couchbase Logs:**
https://gist.github.com/NitzDKoder/d23918d3b9af9860ea4e6c0ccad2bc45

@hideki @pasin please share you thoughts..

Thanks
Nithin

**Comment by hideki** [comment] 2017-08-28 17:13
Hi @NitzDKoder,

Once you encounter this problem, can you try to access Listener URL from the phone browser?
If accessible, the problem could be in the WebView.
If not, Listener's server socket becomes a bad state.

**Comment by NitzDKoder** [comment] 2017-08-28 21:54
@hideki what problem you suspect in webview ? the request is successfully allowed at webview level at whitelistplugin level..

https://github.com/apache/cordova-plugin-whitelist

Will check and confirm if its accessible from browser.

**Comment by NitzDKoder** [comment] 2017-08-29 08:25
@hideki 

**Browser level request work as below:**

	Line 18577: 08-29 13:03:21.741 W/System.err( 9734): [08/29 01:03:21.751] [62] Listener: [REQUEST] (Acme.Utils.ThreadPool(7)-PooledThread: Acme.Serve.Serve$ServeConnection@2dcf3879) GET: https://localdomain:51625/data/s919480109390_ptx1503987993647_meta.doc
	Line 24261: 08-29 13:03:42.751 W/System.err( 9734): [08/29 01:03:42.755] [61] Listener: [REQUEST] (Acme.Utils.ThreadPool(6)-PooledThread: Acme.Serve.Serve$ServeConnection@b14f16c) GET: https://localdomain:51625/data/s919480109390_ptx1503987993647_meta.doc
	Line 53335: 08-29 13:16:19.311 W/System.err( 9734): [08/29 01:16:19.320] [62] Listener: [REQUEST] (Acme.Utils.ThreadPool(7)-PooledThread: Acme.Serve.Serve$ServeConnection@110843ed) GET: https://localdomain:51625/data/s919480109390_ptx1503987993647_meta.doc


**App requests fails to reach local server:**

**1)** 08-29 13:16:22.611 D/[HTML5LOG]( 9734): cblPtxInterface.syncManager()-> doStartPost()-> Start Sync = {"source":"data","target":{"url":"https://AAAAAAAAAAAA:XXXXXXXXXXXXXXXXX@mydomain/data/data"},"continuous":true,"filter":"pushfilter/bystate"}

08-29 13:16:22.611 D/[HTML5LOG]( 9734): cblPtxInterface.syncManager()-> doStartPost()-> Start Sync for PUSH

08-29 13:16:22.611 D/[HTML5LOG]( 9734): ReSTCBL ::: Request started::{"id":"93: POST https://:@localdomain:51625/_replicate"}

08-29 13:16:22.611 D/WhitelistPlugin( 9734): ---------- cblURL: https://:@localdomain:51625/

08-29 13:16:22.611 D/WhitelistPlugin( 9734): ---------- CBL URL allowed to Navigate -----

**2)**  08-29 13:16:25.211 D/[HTML5LOG]( 9734): UI.Util.setHistProxy ----> threadId = %22tel%3A%2B919663733552%22

08-29 13:16:25.211 D/[HTML5LOG]( 9734):  History url = https://:@localdomain:51625/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false


08-29 13:16:25.441 D/WhitelistPlugin( 9734): ---------- cblURL: https://:@localdomain:51625/

08-29 13:16:25.441 D/WhitelistPlugin( 9734): ---------- CBL URL allowed to Navigate -----

**3)** 08-29 13:16:43.321 D/[HTML5LOG]( 9734): ReSTCBL ::change opts : PTX timeout

08-29 13:16:43.341 D/[HTML5LOG]( 9734): ReSTCBL ::: Request started::{"id":"94: GET https://:@localdomain:51625/data/_changes?since=106&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}

08-29 13:16:43.351 D/WhitelistPlugin( 9734): ---------- cblURL: https://:@localdomain:51625/

08-29 13:16:43.351 D/WhitelistPlugin( 9734): ---------- CBL URL allowed to Navigate ----- 


**Detail Logs:**
**ADB:**
https://gist.github.com/NitzDKoder/e3453adaf8cd588fc70864cbfde07b98



**CBL Logs:**

https://gist.github.com/NitzDKoder/6b8b7c7a1bed27f07a186a05b44bb29a




Thanks
Nithin

**Comment by NitzDKoder** [comment] 2017-08-30 17:25
@hideki
The www.google.com works when the issue happens..able to navigate within our webview..
More observation:
a)Issue not seen when webview is downgraded and used stock webview v35 with 5 mins heartbeat.
b)Issue not seen in latest webview with 1 min heartbeat.

**Comment by NitzDKoder** [comment] 2017-09-11 16:12
@hideki issue seen in above b) as well..
How stable is https://github.com/couchbaselabs/TodoLite-PhoneGap/blob/f1a810f9408a9807f3bf25ae69ba1d6a6aaee71c/js/modules.js

This module?

As the request works from browser..can we suspect problem in this .js??

**Comment by hideki** [comment] 2017-09-11 18:24
@NitzDKoder,
I am sorry I am not expert of JavaScript and also modules.js including its underling libraries.
I guess a problem could be in the particular version of Android API, PhoneGap (Cordova) library, or JavaScript codes. However, I can not identify the problem based on current information.

**Comment by NitzDKoder** [comment] 2017-09-19 03:31
@hideki

we control remote replication by REST via listener
Ex: Stop a continuous replication.
Stop Sync = {"target":"ptxdata","source":{"url":"https://AAAAAAAAAAAA:XXXXXXXXXXXXXXXXX@mydomain/data"},"continuous":true,"filter":"sync_gateway/bychannel","query_params":{"channels":"PTX-919480109390-meta-CH,919480109390-CH"}}
[08/28 17:40:08:013] [HTML5LOG] ReSTCBL ::: Request started::{"id":"139: POST https://:@localdomain:14480/_replicate"}

also listen to local db changes by REST via listener
Ex: longpoll _changes.
Line 2050: [08/28 17:54:22:685] [HTML5LOG] ReSTCBL ::: Request started::{"id":"142: GET https://:@localdomain:14480/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll"}

local database view query done using REST request via listener.
Ex: view query.
Line 2553: History url = https://:@localdomain:14480/data/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919663733552%22&reduce=false&group=false

All the request fail sometimes on network tranistions.
We see some exception serve.java.(socket closed, socket timeout and broken pipe.)

Need to check if its cleint or sever socket exception.

https://github.com/couchbase/couchbase-lite-java-listener/blob/master/vendor/tjws/src/java/Acme/Serve/Serve.java#L2130

Workaround:
Currently restarting listener on some request failures.

TODO:
Understand network transitions link to listener socket.Maybe android invalidates all sockets.

Will update more..

Thanks
Nithin

**Comment by hideki** [comment] 2017-09-21 23:19
Hi @NitzDKoder,

I have tried to reproduce this issue with [Todo PhoneGap sample](https://github.com/couchbaselabs/TodoLite-PhoneGap). So far, I could not reproduce this issue. I am using Nexus 6 with Android 7.1.1.

How is your test environment?

Thanks,
Hideki

**Comment by hideki** [comment] 2017-09-21 23:45
Hi @NitzDKoder,

I have another question.

How can I create the state of `idle the rest request`?

> After idle the REST request from HTML/JS fails to get response from server.

**Comment by NitzDKoder** [comment] 2017-09-22 14:37
@hideki 
Test environment:
1)_changes is with below parameter.
timeout 4 mins.
no heartbeat sent.

"http://127.0.0.1:27458/ptxdata/_changes?since=25718&include_docs=true&style=main_only&timeout=240000&feed=longpoll"

2)https://github.com/couchbaselabs/TodoLite-PhoneGap/blob/f1a810f9408a9807f3bf25ae69ba1d6a6aaee71c/js/modules.js#L1205

DEFAULT_TIMEOUT = 5 * 60 * 1000 // 5 minutes

3) different type of doc data is in DB say count is 10000 documents. more data will pushed to DB by remote or locally. say every 10 secs.



4)Every 10 secs a view query request is done using below. 

ex : http://127.0.0.1:27458/ptxdata/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919888881189%3Bkn-corp-groups%3D16_1328%22&reduce=false&group=false


returns say 1000 docs as view data.

5)Doing 4# and 3# make the network transitions i.e wifi to 3G or vice-versa. Aeroplane mode on- off.

  
Thanks
Nithin

**Comment by hideki** [comment] 2017-09-22 15:19
@NitzDKoder,
I'd like to know Android device information to reproduce this issue.

**Comment by NitzDKoder** [comment] 2017-09-22 15:29
@hideki we see this in samsung devices(Note 4, Note 5, S8).

**Comment by hideki** [comment] 2017-09-22 15:52
@NitzDKoder How about Android OS Version or Android API version?

**Comment by NitzDKoder** [comment] 2017-09-22 16:46
@hideki (Note 4(5.0.1), Note 5(7.0), S8(7.0)).

**Comment by hideki** [comment] 2017-09-22 17:21
@NitzDKoder 
Thank you for your inputs.
It seems this problem occurs with latest Android OSs and latest devices.

**Comment by NitzDKoder** [comment] 2017-09-22 17:38
@Note 4 has old OS(5.0.1), could be webview behaviour as it gets updated from playstore or chrome update.


On server stop and start the requests works.As the server URL is different.



**Other suspect:**
1)When the app Does REST via 
https://github.com/couchbaselabs/TodoLite-PhoneGap/blob/f1a810f9408a9807f3bf25ae69ba1d6a6aaee71c/js/modules.js
2) ~4 client sockets get open here
https://github.com/couchbase/couchbase-lite-java-listener/blob/master/vendor/tjws/src/java/Acme/Serve/Serve.java#L848
3)later these will be reused for next requests(like a connectionpool of okhttp).(on timeout these might get closed)
4)Is Javascript writing to closed socket?
4)When the failure happens we do not see anything in PCAP either.

Please get more thoughts with JavaScript experts within your team..We have production issue going on with this.


Thanks
Nithin

**Comment by hideki** [comment] 2017-09-22 17:55
> 4)Is Javascript writing to closed socket?

Does Ajax method fail when it sends the request?

Does JavaScript support Socket Timeout setting? I assume Ajax could fail as soon as timeout occurs after sending the request to the closed connection. If my memory is correct, the application set 5min for a timeout, can you try to set it 10 or 20 sec?

**Comment by hideki** [comment] 2017-09-22 18:17
Hi @NitzDKoder,

To capture the thread-dump, can you start the application from the Android Studio instead of starting from PhoneGap command? To narrow down where the problem is, thread-dump is really useful.

**Comment by hideki** [comment] 2017-09-22 18:35
Hi @NitzDKoder,
I just re-read/reviewed the [original your message](https://github.com/couchbase/couchbase-lite-java-listener/issues/83#issue-253349069) and also log file you attached. 
Listener received the following request.
```
/data/_changes?since=97&include_docs=true&style=main_only&heartbeat=300000&feed=longpoll
```

Also, Listener was sending the heart-beat to the client (JS) every a minute.
```
[08/28 06:29:42.869] [89] Router: [com.couchbase.lite.router.Router$7@28e4e032] Changes heartbeat sent!
[08/28 06:29:42.916] [88] Router: [com.couchbase.lite.router.Router$7@38b4003d] Changes heartbeat sent!
[08/28 06:29:43.088] [86] Router: [com.couchbase.lite.router.Router$7@288cdae8] Changes heartbeat sent!
[08/28 06:34:22.499] [81] Router: [com.couchbase.lite.router.Router$7@306561b] Changes heartbeat sent!
[08/28 06:34:42.651] [82] Router: [com.couchbase.lite.router.Router$7@3e5fb364] Changes heartbeat sent!
[08/28 06:34:42.782] [85] Router: [com.couchbase.lite.router.Router$7@32d075c9] Changes heartbeat sent!
[08/28 06:34:42.868] [89] Router: [com.couchbase.lite.router.Router$7@28e4e032] Changes heartbeat sent!
[08/28 06:34:42.916] [88] Router: [com.couchbase.lite.router.Router$7@38b4003d] Changes heartbeat sent!
[08/28 06:34:43.088] [86] Router: [com.couchbase.lite.router.Router$7@288cdae8] Changes heartbeat sent!
```
From this log, I could observe the Listener handled 6 unique `/_changes` requests. Router instances are different.

Without checking thread-dump, I can not tell. But I wonder if all threads of Listener had been consumed that point.

**Comment by NitzDKoder** [comment] 2017-09-22 18:57
https://127.0.0.1:25522/data/_changes?since=26202&include_docs=true&style=main_only&timeout=240000&feed=longpoll

We dont use heatbeat value instead use timeout so that we get 200ok every 4 mins.



1)@[09/22 14:27:10:109] [HTML5LOG] UI.Util.setHistProxy ----> threadId = %22tel%3A%2B919888881189%3Bkn-corp-groups%3D16_1328%22
 History url = https://:@127.0.0.1:25522/ptxdata/_design%2FgetHistory/_view/getHistory?key=%22tel%3A%2B919888881189%3Bkn-corp-groups%3D16_1328%22&reduce=false&group=false

JS request.


2) 09/22 14:27:10:267] WhitelistPlugin ---------- CBL URL allowed to Navigate -

Android Webview level allowed to navigate

3) Same is not see in CBL and PCAP does not show that as well.

[no_request.txt](https://github.com/couchbase/couchbase-lite-java-listener/files/1325532/no_request.txt)
ogs.

**Comment by NitzDKoder** [comment] 2017-09-22 19:00
As per https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/status
request might get status of 0.
**It is worth noting that browsers report a status of 0 in case of XMLHttpRequest errors too.**


will get the thread dump ASAP.

**Comment by hideki** [comment] 2017-09-22 19:44
Hi @NitzDKoder,

Can you also check error, abort, and timeout events? They might give us the hints.
https://xhr.spec.whatwg.org/#the-status-attribute

**Comment by hideki** [comment] 2017-09-22 20:29
Hi @NitzDKoder 

It seems I skipped to read [your comment](https://github.com/couchbase/couchbase-lite-java-listener/issues/83#issuecomment-326061308). You commented this issue is not seen with `stock webview v35`. It indicates this AJAX issue could be caused by WebView.

**Comment by NitzDKoder** [comment] 2017-09-26 14:28
@hideki its seen in OLD webview too.. it was the initial analysis...later we found its seen in old WEBVIEW too..

**Comment by hideki** [comment] 2017-09-26 16:12
@NitzDKoder thank you for your additional input.

**Comment by pasin** [comment] 2017-10-10 22:59
Normally each web browser including web view has a limit number of concurrent HTTP requests sent per host name; normally around 6 - 8. I'm wondering if there could be any pending HTTP requests (especially _changes requests) that have been forgotten. @NitzDKoder as @hideki said, could you please capture the thread dump while the issue is happening; it should give us some clues what going on. As you also check the PCAP, do you see any pending requests?

**Comment by NitzDKoder** [comment] 2017-10-12 08:27
@pasin able to get the Thread Dump at this point.. but PCAP does not show this requests.. Looks they are Qued  at Webview level..

**Comment by hideki** [comment] 2017-10-12 22:15
Hi @NitzDKoder, 
WebView is a third-party component. And the issue is not caused by CBL. 
I will close this ticket.
Thanks!

**Closed by hideki** 2017-10-12 22:15 UTC
Labels: backlog, ffc, needsmoreinfo, P1: high, reproduce/investigate
